"""
Phase 3: Automated Statutory Report Generation.

One-click PDF export of the statutory paper-equivalent output the site
was previously only digitizing on-screen: a filled Form VII corrective
order for a single violation, and a monthly compliance summary per mine
(or across all mines for DGMS/corporate). This is what actually satisfies
the PS's "minimize manual paperwork" requirement.

Uses reportlab (pure-Python, no system dependency) so PDF generation
works out of the box in any deployment.
"""
import io
from datetime import datetime, timedelta
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Optional

# reportlab is imported defensively rather than at module top-level: if
# `pip install -r requirements.txt` hasn't been re-run after pulling in
# Phase 3, an unconditional top-level `import reportlab` here would raise
# ImportError while api/v1/__init__.py is still building the router table
# — which takes the ENTIRE backend down at startup, not just this feature.
# Deferring it means a missing reportlab only disables report generation
# (with a clear 503 message) and every other screen keeps working.
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    _REPORTLAB_AVAILABLE = True
except ImportError:
    _REPORTLAB_AVAILABLE = False

from app.database import get_db
from app.models.violation import Violation, ViolationStatus, ViolationSeverity
from app.models.action import CorrectiveAction
from app.models.mine import Mine
from app.models.environmental import EnvironmentalRecord
from app.models.production import ProductionRecord
from app.models.contractor import Contractor
from app.utils.audit import write_audit

router = APIRouter(prefix="/reports", tags=["Phase 3: Automated Report Generation"])

if _REPORTLAB_AVAILABLE:
    STYLES = getSampleStyleSheet()
    TITLE_STYLE = ParagraphStyle("KRTitle", parent=STYLES["Title"], fontSize=14, textColor=colors.HexColor("#0f172a"), alignment=TA_CENTER)
    SUB_STYLE = ParagraphStyle("KRSub", parent=STYLES["Normal"], fontSize=9, textColor=colors.HexColor("#475569"), alignment=TA_CENTER)
    H2_STYLE = ParagraphStyle("KRH2", parent=STYLES["Heading2"], fontSize=11, textColor=colors.HexColor("#0f172a"), spaceBefore=10, spaceAfter=4)
    BODY_STYLE = ParagraphStyle("KRBody", parent=STYLES["Normal"], fontSize=9, leading=13, alignment=TA_LEFT)
    SMALL_STYLE = ParagraphStyle("KRSmall", parent=STYLES["Normal"], fontSize=7.5, textColor=colors.HexColor("#64748b"))


def _letterhead(elements, subtitle: str):
    elements.append(Paragraph("GOVERNMENT OF INDIA — MINISTRY OF COAL", SUB_STYLE))
    elements.append(Paragraph("Directorate General of Mines Safety (DGMS)", SUB_STYLE))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph("KHADAN RAKSHAK — Statutory Compliance & Governance Platform", TITLE_STYLE))
    elements.append(Paragraph(subtitle, SUB_STYLE))
    elements.append(Spacer(1, 6))
    elements.append(HRFlowable(width="100%", thickness=1.2, color=colors.HexColor("#f59e0b")))
    elements.append(Spacer(1, 10))


def _footer_note(elements, generated_for: str = ""):
    elements.append(Spacer(1, 16))
    elements.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#cbd5e1")))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        f"Auto-generated by KHADAN RAKSHAK on {datetime.now().strftime('%d %b %Y, %H:%M IST')}. "
        f"This is a system-generated statutory document; entries are sourced live from the compliance "
        f"ledger and are logged in the tamper-evident audit trail. {generated_for}",
        SMALL_STYLE
    ))


def _kv_table(pairs, col_widths=None):
    if col_widths is None:
        col_widths = (45 * mm, 120 * mm)  # resolved lazily — mm only exists if reportlab loaded
    rows = [[Paragraph(f"<b>{k}</b>", BODY_STYLE), Paragraph(str(v) if v is not None else "—", BODY_STYLE)] for k, v in pairs]
    t = Table(rows, colWidths=list(col_widths))
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
    ]))
    return t


@router.get("/status")
def reports_status():
    return {"reportlab_available": _REPORTLAB_AVAILABLE}


def _require_reportlab():
    if not _REPORTLAB_AVAILABLE:
        raise HTTPException(
            status_code=503,
            detail="reportlab is not installed on this server. Run 'pip install -r requirements.txt' "
                   "(or 'pip install reportlab') in the backend environment and restart, then retry."
        )


@router.get("/form-vii/{violation_id}")
def generate_form_vii(violation_id: str, db: Session = Depends(get_db)):
    """One-click PDF of the Form VII corrective order + closure record for a single violation."""
    _require_reportlab()
    v = db.query(Violation).filter(Violation.id == violation_id).first()
    if not v:
        raise HTTPException(404, "Violation not found")
    actions = db.query(CorrectiveAction).filter(CorrectiveAction.violation_id == violation_id).all()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18*mm, bottomMargin=16*mm, leftMargin=18*mm, rightMargin=18*mm)
    elements = []
    _letterhead(elements, f"FORM VII — Statutory Corrective Order &amp; Closure Record ({v.id})")

    elements.append(_kv_table([
        ("Violation ID", v.id),
        ("Mine", v.mine_name),
        ("Regulation", v.regulation),
        ("Category", v.category),
        ("Title", v.title),
        ("Severity", v.severity.value if hasattr(v.severity, "value") else v.severity),
        ("Status", v.status.value if hasattr(v.status, "value") else v.status),
        ("Reported On", v.created_at.strftime("%d %b %Y, %H:%M IST") if v.created_at else "—"),
        ("Statutory Deadline", v.deadline.strftime("%d %b %Y, %H:%M IST") if v.deadline else "—"),
        ("Assigned To", v.assigned_to),
        ("GPS Location", v.gps_coordinates),
    ]))

    elements.append(Paragraph("Description of Non-Compliance", H2_STYLE))
    elements.append(Paragraph(v.description or "—", BODY_STYLE))

    if actions:
        elements.append(Paragraph("Corrective Action Order", H2_STYLE))
        for a in actions:
            elements.append(_kv_table([
                ("Assigned Fixer", a.assigned_to_name),
                ("Instructions", a.instructions or "—"),
                ("Deadline", a.deadline.strftime("%d %b %Y, %H:%M IST") if a.deadline else "—"),
                ("Completed", "Yes" if a.is_completed else "No"),
                ("Fix Remarks", a.fix_remarks or "—"),
                ("Verified", "Yes" if a.is_verified else "No"),
                ("Supervisor Remarks", a.supervisor_remarks or "—"),
            ]))

    if v.status == ViolationStatus.CLOSED:
        elements.append(Paragraph("Closure Certification", H2_STYLE))
        elements.append(Paragraph(
            f"This violation was verified and formally closed on "
            f"{v.closed_at.strftime('%d %b %Y, %H:%M IST') if v.closed_at else 'N/A'} under the "
            f"Supervisor Verification (Form VII-A) workflow.", BODY_STYLE
        ))

    if v.red_alert_issued or v.dgms_alert_sent or v.stoppage_warning_issued:
        elements.append(Paragraph("Statutory Escalations on Record", H2_STYLE))
        esc_rows = []
        if v.dgms_alert_sent:
            esc_rows.append(("DGMS Alert", f"{v.dgms_alert_level or ''} — {v.dgms_alert_notes or ''}"))
        if v.stoppage_warning_issued:
            esc_rows.append(("Work-Stoppage Directive (Sec. 22)", v.stoppage_directive_text or "Issued"))
        if v.red_alert_issued:
            esc_rows.append(("Statutory Red Alert", v.red_alert_reason or "Issued"))
        elements.append(_kv_table(esc_rows))

    _footer_note(elements, f"Violation reference: {v.id}.")
    doc.build(elements)
    buf.seek(0)

    write_audit(db, "REPORT", v.id, "FORM_VII_GENERATED", actor="System", mine_name=v.mine_name,
                payload_summary=f"Form VII PDF generated for {v.id}")

    filename = f"Form_VII_{v.id}.pdf"
    return StreamingResponse(buf, media_type="application/pdf",
                              headers={"Content-Disposition": f'attachment; filename="{filename}"'})


@router.get("/monthly-summary")
def generate_monthly_summary(mine: Optional[str] = "ALL", user_role: Optional[str] = None, user_mine: Optional[str] = None, db: Session = Depends(get_db)):
    """Monthly statutory compliance summary — safety, environment, production, labour, one PDF per mine or consolidated."""
    _require_reportlab()
    if user_role in {"manager", "supervisor"} and user_mine: mine = user_mine
    now = datetime.now()
    cutoff_30d = now - timedelta(days=30)

    mines_q = db.query(Mine)
    if mine and mine != "ALL":
        mines_q = mines_q.filter(Mine.name.like(f"{mine.split(' ')[0]}%"))
    mines = mines_q.all()
    if not mines:
        raise HTTPException(404, "No matching mine(s) found")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18*mm, bottomMargin=16*mm, leftMargin=18*mm, rightMargin=18*mm)
    elements = []
    period_label = f"{cutoff_30d.strftime('%d %b %Y')} – {now.strftime('%d %b %Y')}"
    _letterhead(elements, f"Monthly Statutory Compliance Summary ({period_label})")

    for m in mines:
        elements.append(Paragraph(f"{m.name}", H2_STYLE))
        elements.append(_kv_table([
            ("Subsidiary", m.subsidiary), ("Zone", m.zone), ("Type", m.mine_type),
            ("Gassy Category", m.gassy_category),
            ("Compliance Rate", f"{m.compliance_rate:.1f}%"),
            ("AI Composite Risk Score", f"{m.risk_score:.1f} / 100"),
            ("Open Violations", m.open_violations_count),
            ("Critical Violations", m.critical_violations_count),
        ]))

        viols = db.query(Violation).filter(Violation.mine_name.like(f"{m.name.split(' ')[0]}%")).all()
        closed_30d = sum(1 for v in viols if v.status == ViolationStatus.CLOSED and v.closed_at and
                          (v.closed_at.replace(tzinfo=None) if v.closed_at.tzinfo else v.closed_at) >= cutoff_30d)
        reported_30d = sum(1 for v in viols if v.created_at and
                            (v.created_at.replace(tzinfo=None) if v.created_at.tzinfo else v.created_at) >= cutoff_30d)

        env = db.query(EnvironmentalRecord).filter(EnvironmentalRecord.mine_name.like(f"{m.name.split(' ')[0]}%")).all()
        exceeding = sum(1 for e in env if e.status == "EXCEEDS_LIMIT")

        prod = db.query(ProductionRecord).filter(ProductionRecord.mine_name.like(f"{m.name.split(' ')[0]}%")).all()
        overproduction_days = sum(1 for p in prod if p.is_overproduction)

        contractors = db.query(Contractor).filter(Contractor.mine_name.like(f"{m.name.split(' ')[0]}%")).all()
        flagged = sum(1 for c in contractors if c.status in ("FLAGGED", "BLACKLISTED"))

        elements.append(_kv_table([
            ("Violations Reported (30d)", reported_30d),
            ("Violations Closed (30d)", closed_30d),
            ("Environmental Readings Exceeding Limit", exceeding),
            ("Production Days Over Approved Capacity", overproduction_days),
            ("Contractors Flagged / Blacklisted", flagged),
        ]))
        elements.append(Spacer(1, 6))
        elements.append(HRFlowable(width="100%", thickness=0.4, color=colors.HexColor("#e2e8f0")))

    _footer_note(elements, f"Scope: {mine if mine != 'ALL' else 'All CIL Subsidiaries'}.")
    doc.build(elements)
    buf.seek(0)

    write_audit(db, "REPORT", mine or "ALL", "MONTHLY_SUMMARY_GENERATED", actor="System",
                payload_summary=f"Monthly summary generated for {mine or 'ALL'}")

    safe_scope = (mine or "ALL").replace(" ", "_").replace("/", "-")
    filename = f"Monthly_Compliance_Summary_{safe_scope}_{now.strftime('%Y%m')}.pdf"
    return StreamingResponse(buf, media_type="application/pdf",
                              headers={"Content-Disposition": f'attachment; filename="{filename}"'})
